name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Access FIREBASE_API_KEY
      env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      run: echo FIREBASE_API_KEY=\"$FIREBASE_API_KEY\" > ./local.properties

    - name: Access FIREBASE_APPLICATION_ID
      env:
          FIREBASE_APPLICATION_ID: ${{ secrets.FIREBASE_APPLICATION_ID }}
      run: echo FIREBASE_APPLICATION_ID=\"$FIREBASE_APPLICATION_ID\" > ./local.properties

    - name: Access FIREBASE_PROJECT_ID
      env:
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      run: echo FIREBASE_PROJECT_ID=\"$FIREBASE_PROJECT_ID\" > ./local.properties

    - name: Add Google Services Json File
      env: 
          DATA: ${{ secrets.GOOGLESERVICESJSON }}
      run: echo $DATA > /home/runner/work/InstagramClone/InstagramClone/app/src/google-services.json

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean build
      
    - name: Run local tests
      if: always()
      run: ./gradlew testDebugUnitTest

    - name: Upload test results (XML)
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: '**/build/test-results/test*UnitTest/**.xml'
  
